#file: noinspection SpringBootApplicationYaml
server:
  port: 8091
  undertow:
    always-set-keep-alive: false
    threads:
      io: 8
      worker: 20

spring:
  liquibase:
    enabled: true
    default-schema: ${DATABASE_SCHEMA}

  jpa:
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_JWT_ISSUER_URI}

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      poolName: SpringBootHikariCP
      schema: ${DATABASE_SCHEMA}
      maxLifetime: '1800000'  # 30 minutos
      connectionTimeout: '5000'  # 5 segundos
      idleTimeout: '10000'  # 10 segundos
      minimumIdle: '5'
      maximumPoolSize: '15'

logging:
  level:
    root: INFO
    com.manuela.meucaixa: TRACE
    org.springframework: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type: WARN

application:
  cors:
    allowed-origins:
      - "http://localhost:5173"

  keycloak:
    base-url: ${KEYCLOAK_BASE_URL}
    master-username: ${KEYCLOAK_USERNAME}
    master-password: ${KEYCLOAK_PASSWORD}
    client-id: ${KEYCLOAK_CLIENT_ID}
    web-client-id: ${KEYCLOAK_WEB_CLIENT_ID}
    web-client-secret: ${KEYCLOAK_WEB_CLIENT_SECRET}
    scope: ${KEYCLOAK_SCOPE}
