#file: noinspection SpringBootApplicationYaml
server:
  port: 8091
  undertow:
    always-set-keep-alive: false
    threads:
      io: 8
      worker: 20

spring:
  liquibase:
    enabled: true
    default-schema: meu_caixa

  jpa:
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/meucaixa

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/meucaixa
    username: admin
    password: admin
    hikari:
      poolName: SpringBootHikariCP
      schema: meu_caixa
      maxLifetime: '1800000'  # 30 minutos
      connectionTimeout: '5000'  # 5 segundos
      idleTimeout: '10000'  # 10 segundos
      minimumIdle: '5'
      maximumPoolSize: '15'

logging:
  level:
    root: INFO
    com.manuela.meucaixa: TRACE
    org.springframework: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type: WARN

application:

  cors:
    allowed-origins:
      - "http://localhost:5173"

  keycloak:
    base-url: "http://localhost:8080"
    master-username: admin
    master-password: admin
    client-id: admin-cli
